# Generated by Django 4.0.3 on 2022-06-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheMoreYouKnow', '0002_content_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='user_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
