# Generated by Django 4.0.3 on 2022-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheMoreYouKnow', '0004_alter_content_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
